spring:
  application:
    name: academic-service

  r2dbc:
    username: academic_user
    password: ${ACADEMIC_DB_PASSWORD:academic_pwd}
    properties:
      schema: academic_schema
    url: r2dbc:postgresql://${DB_HOST:localhost}:5432/emis_db?schema=academic_schema
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10

  flyway:
    user: academic_user
    password: ${FLYWAY_DB_PASSWORD:academic_pwd}
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/emis_db
    schemas: academic_schema
    default-schema: academic_schema
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false

  cloud:
    stream:
      bindings:
        hrEvents-in-0:
          destination: hr.events.v1
          group: academic-service
          content-type: application/json
        attendance-out-0:
          destination: attendance.events.v1

      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}



#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/emis
#  lifecycle:
#    timeout-per-shutdown-phase: 15s


server:
  port: 8084
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

#springdoc:
#  swagger-ui:
#    path: /swagger-ui

# application-prod.yml
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http.converter: DEBUG
    org.springframework.validation: DEBUG
    org.springframework.web.reactive.result.method.annotation: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    org.flywaydb: DEBUG


emis:
  services:
    school-configuration:
      base-url: ${EMIS_SERVICE_URL:http://localhost:8082}
      get-school-details-url: ${emis.services.school-configuration.base-url}/api/v1/schools/{schoolCode}
      validate-school-exists-url: ${emis.services.configuration.base-url}/api/v1/schools/validate/{schoolCode}

    student-configuration:
      base-url: ${EMIS_SERVICE_URL:http://localhost:8083}
      get-student-details-url: ${emis.services.student-configuration.base-url}/api/v1/students
      get-active-enrollment-url: ${emis.services.student-configuration.base-url}/api/v1/students/{studentNumber}/enrollments/current

    timeout: 5
